cmake_minimum_required(VERSION 3.30)
project(libcompression VERSION 0.1.0 LANGUAGES CXX C)

option(LIBCOMPRESSION_ENABLE_TESTS "Enable tests for libcompression" on)
option(LIBCOMPRESSION_ENABLE_BENCHMARKS "Enable benchmarks for libcompression" on)
option(LIBCOMPRESSION_ENABLE_CODE_COVERAGE "Enable code coverage for libcompression (requires lcov/genhtml)" off)
option(LIBCOMPRESSION_ENABLE_LTO "Enable Link Time Optimization (LTO)" off)

option(LIBCOMPRESSION_DISABLE_BMI2 "Enable BMI2 optimizations" on)
option(LIBCOMPRESSION_DISABLE_AVX2 "Enable AVX2 optimizations" off)
option(LIBCOMPRESSION_DISABLE_AVX512 "Enable AVX512 optimizations" off)

option(LIBCOMPRESSION_ENABLE_FORTRAN_BINDINGS "Build Fortran bindings for libcompression" off)

option(LIBCOMPRESSION_ENABLE_DOXYGEN "Build documentation with Doxygen." off)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")

find_program(CCACHE_PROGRAM ccache)
if (CCACHE_PROGRAM)
    message(STATUS "Found ccache: ${CCACHE_PROGRAM}")
    set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
endif ()

include(CTest)

include(GitVersion)
get_git_version(GIT_VERSION)

if ("${GIT_VERSION}" STREQUAL "v0.0.0")
    set(VERSION "${libcompression_VERSION}")
else ()
    set(VERSION "${GIT_VERSION}")
endif ()

string(STRIP ${VERSION} VERSION)
if (VERSION MATCHES v[^-]*-)
    string(REGEX REPLACE "v([^-]*)-([0-9]+)-.*" "\\1.\\2" NORMALIZED_VERSION ${VERSION})
else ()
    string(REGEX REPLACE "v(.*)" "\\1" NORMALIZED_VERSION ${VERSION})
endif ()
message(STATUS "Libcompression version: ${VERSION}, normalized to ${NORMALIZED_VERSION}")

set(BENCHMARK_CXX_STANDARD 20)

set(CMAKE_CXX_STANDARD ${BENCHMARK_CXX_STANDARD})
set(CMAKE_CXX_STANDARD_REQUIRED YES)
set(CMAKE_CXX_EXTENSIONS OFF)

include(AddCXXCompilerFlag)
if (MSVC)
    message(FATAL_ERROR "MSVC compiler is not supported")
else ()
    add_cxx_compiler_flag(-Wall)
    add_cxx_compiler_flag(-Wextra)
    add_cxx_compiler_flag(-Wshadow)
    add_cxx_compiler_flag(-Wfloat-equal)
    add_cxx_compiler_flag(-Wold-style-cast)
    add_cxx_compiler_flag(-Wconversion)
    # add_cxx_compiler_flag(-Werror)
    # add_cxx_compiler_flag(-pedantic)
    # add_cxx_compiler_flag(-pedantic-errors)
    # add_cxx_compiler_flag(-Wshorten-64-to-32)
    add_cxx_compiler_flag(-fstrict-aliasing)
    # add_cxx_compiler_flag(-Wthread-safety)
    add_cxx_compiler_flag(-Wignored-attributes)

    if (LIBCOMPRESSION_ENABLE_LTO)
        add_cxx_compiler_flag(-flto=auto)
        add_cxx_compiler_flag(-Wno-lto-type-mismatch)
        if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
            find_program(GCC_AR gcc-ar)
            if (GCC_AR)
                set(CMAKE_AR ${GCC_AR})
            endif ()
            find_program(GCC_RANLIB gcc-ranlib)
            if (GCC_RANLIB)
                set(CMAKE_RANLIB ${GCC_RANLIB})
            endif ()
        elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
            find_program(LLVM_AR llvm-ar)
            if (LLVM_AR)
                set(CMAKE_AR ${LLVM_AR})
            endif ()
            find_program(LLVM_RANLIB llvm-ranlib)
            if (LLVM_RANLIB)
                set(CMAKE_RANLIB ${LLVM_RANLIB})
            endif ()
        endif ()
    endif ()
endif ()

#if (LIBCOMPRESSION_DISABLE_BMI2)
#    add_definitions(-DLIBCOMPRESSION_DISABLE_BMI2)
#endif ()
#if (LIBCOMPRESSION_DISABLE_AVX2)
#    add_definitions(-DLIBCOMPRESSION_DISABLE_AVX2)
#endif ()
#if (LIBCOMPRESSION_DISABLE_AVX512)
#    add_definitions(-DLIBCOMPRESSION_DISABLE_AVX512)
#endif ()
#if (LIBCOMPRESSION_DISABLE_AVX512_VBMI)
#    add_definitions(-DLIBCOMPRESSION_DISABLE_AVX512_VBMI)
#endif ()

#if (LIBCOMPRESSION_ENABLE_BMI2)
#    add_cxx_compiler_flag(-mbmi2)
#    add_cxx_compiler_flag(-mavx2)
#    add_compile_definitions(LIBCOMPRESSION_ENABLE_BMI2_OPTIMIZATIONS)
#    message(STATUS "BMI2 optimizations enabled")
#endif ()
#
#if (LIBCOMPRESSION_ENABLE_AVX2)
#    add_cxx_compiler_flag(-mavx2)
#    add_compile_definitions(LIBCOMPRESSION_ENABLE_AVX2_OPTIMIZATIONS)
#    message(STATUS "AVX2 optimizations enabled")
#endif ()
#
#if (LIBCOMPRESSION_ENABLE_AVX512)
#    add_cxx_compiler_flag(-mavx2)
#    add_cxx_compiler_flag(-mavx512f)
#    add_cxx_compiler_flag(-mavx512bw)
#    add_cxx_compiler_flag(-mavx512dq)
#    add_cxx_compiler_flag(-mavx512vl)
#    add_cxx_compiler_flag(-mavx512cd)
#    add_compile_definitions(LIBCOMPRESSION_ENABLE_AVX512_OPTIMIZATIONS)
#    message(STATUS "AVX512 optimizations enabled")
#
#    if (LIBCOMPRESSION_ENABLE_AVX512_VBMI)
#        add_cxx_compiler_flag(-mavx512vbmi)
#        message(STATUS "AVX512 VBMI optimizations enabled")
#    endif ()
#endif ()

include_directories(${PROJECT_SOURCE_DIR}/include)

add_subdirectory(src)

if (LIBCOMPRESSION_ENABLE_FORTRAN_BINDINGS)
    message(STATUS "Building Fortran bindings for libcompression")
    include(CMakeAddFortranSubdirectory)
    cmake_add_fortran_subdirectory(bindings/fortran NO_EXTERNAL_INSTALL)
endif ()

if (LIBCOMPRESSION_ENABLE_TESTS)
    enable_testing()
    add_subdirectory(tests)

    if (LIBCOMPRESSION_ENABLE_BENCHMARKS)
        add_subdirectory(benchmarks)
    endif ()
endif ()