if (NOT DEFINED PERNIX_BUILD_DIR)
    message(FATAL_ERROR "PERNIX_BUILD_DIR is required")
endif ()
if (NOT DEFINED PERNIX_CONSUMER_SOURCE_DIR)
    message(FATAL_ERROR "PERNIX_CONSUMER_SOURCE_DIR is required")
endif ()
if (NOT DEFINED PERNIX_CONSUMER_BUILD_DIR)
    message(FATAL_ERROR "PERNIX_CONSUMER_BUILD_DIR is required")
endif ()
if (NOT DEFINED PERNIX_INSTALL_PREFIX)
    message(FATAL_ERROR "PERNIX_INSTALL_PREFIX is required")
endif ()

set(PERNIX_CONFIG_ARG)
if (DEFINED PERNIX_TEST_CONFIG AND NOT PERNIX_TEST_CONFIG STREQUAL "")
    list(APPEND PERNIX_CONFIG_ARG --config "${PERNIX_TEST_CONFIG}")
endif ()

file(REMOVE_RECURSE "${PERNIX_INSTALL_PREFIX}" "${PERNIX_CONSUMER_BUILD_DIR}")

execute_process(
        COMMAND "${CMAKE_COMMAND}" --install "${PERNIX_BUILD_DIR}" --prefix "${PERNIX_INSTALL_PREFIX}" ${PERNIX_CONFIG_ARG}
        RESULT_VARIABLE PERNIX_INSTALL_RESULT
)
if (NOT PERNIX_INSTALL_RESULT EQUAL 0)
    message(FATAL_ERROR "Installing pernix for consumer test failed")
endif ()

set(PERNIX_COMPILER_ARGS)
if (DEFINED PERNIX_C_COMPILER AND NOT PERNIX_C_COMPILER STREQUAL "")
    list(APPEND PERNIX_COMPILER_ARGS "-DCMAKE_C_COMPILER=${PERNIX_C_COMPILER}")
endif ()
if (DEFINED PERNIX_CXX_COMPILER AND NOT PERNIX_CXX_COMPILER STREQUAL "")
    list(APPEND PERNIX_COMPILER_ARGS "-DCMAKE_CXX_COMPILER=${PERNIX_CXX_COMPILER}")
endif ()

execute_process(
        COMMAND "${CMAKE_COMMAND}"
        -S "${PERNIX_CONSUMER_SOURCE_DIR}"
        -B "${PERNIX_CONSUMER_BUILD_DIR}"
        "-DCMAKE_PREFIX_PATH=${PERNIX_INSTALL_PREFIX}"
        "-DCMAKE_BUILD_TYPE=Release"
        ${PERNIX_COMPILER_ARGS}
        RESULT_VARIABLE PERNIX_CONFIGURE_RESULT
)
if (NOT PERNIX_CONFIGURE_RESULT EQUAL 0)
    message(FATAL_ERROR "Configuring installed pernix consumer failed")
endif ()

execute_process(
        COMMAND "${CMAKE_COMMAND}" --build "${PERNIX_CONSUMER_BUILD_DIR}" --config Release --parallel 12
        RESULT_VARIABLE PERNIX_BUILD_RESULT
)
if (NOT PERNIX_BUILD_RESULT EQUAL 0)
    message(FATAL_ERROR "Building installed pernix consumer failed")
endif ()

execute_process(
        COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${PERNIX_CONSUMER_BUILD_DIR}" --output-on-failure
        RESULT_VARIABLE PERNIX_TEST_RESULT
)
if (NOT PERNIX_TEST_RESULT EQUAL 0)
    message(FATAL_ERROR "Running installed pernix consumer tests failed")
endif ()
